server.port: 9001

spring:
  application.name: order-inquiry

  cloud:
    stream:
      kafka.streams:
        binder:
          brokers: 192.168.1.112:9092 # just to use it in the service app, Its already 'localhost:9092' by default
          auto-add-partitions: true
          min-partition-count: 6
          state-store-retry:
            max-attempts: 10
            backoff-period: 500
          configuration:
            application.id: ${spring.application.name}
            application.server: localhost:${server.port} # for InteractiveQueryService to describe itself
            state.dir: state-${spring.application.name}-${server.port} # to give a unique dir name in case you run multiple of this app on the same machine
            default.key.serde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            commit.interval.ms: 1000
            auto.offset.reset: latest